name: Relase distribution

on:
  push:
    branches:
    - '**'
  delete:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive

    - name: Compile
      run: yarn ttsc

    - name: Release
      uses: './.'
      with:
        push-branch: release-{branch}
        js-override-main: main.ts

  rebuild:
    runs-on: ubuntu-latest
    needs: [build_and_push]

    steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract
      id: extract
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Checkout pre-built
      uses: actions/checkout@v3
      with:
        ref: release-${{ steps.extract.outputs.branch }}
        path: prebuilt

    - name: Release
      uses: './prebuilt'
      if: github.event_name != 'delete'
      with:
        push-branch: release-{branch}
        js-override-main: main.ts
